const jokes = [
    "Why don't skeletons fight each other? They don't have the guts.",
    "Why don't oysters donate to charity? Because they're shellfish.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "I asked my dog what's two minus two. He said nothing.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "I used to play piano by ear, but now I use my hands.",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "I told my wife she was getting too emotional, so she told me to go to my room.",
    "I can't trust stairs. They're always up to something.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "I told my computer I needed a break, and now it won’t stop sending me kit-kats.",
    "I made a pun about the wind, but it blows.",
    "Why don’t skeletons fight each other? They don’t have the stomach for it.",
    "I couldn't figure out why I didn't like my steak. Then it dawned on me.",
    "What do you call fake spaghetti? An impasta.",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "I have a joke about construction, but I’m still working on it.",
    "I used to be a baker, but I couldn't make enough dough.",
    "I couldn’t figure out how to put my seatbelt on. Then it clicked.",
    "What’s brown and sticky? A stick.",
    "I used to be a velcro salesman, but I couldn’t stick with it.",
    "I don’t trust people who do acupuncture. They’re back stabbers.",
    "What do you call a pile of cats? A meow-tain.",
    "How does Moses make his coffee? Hebrews it.",
    "I don't trust people who do yoga. They're always stretching the truth.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "I have a joke about a pencil, but it’s pointless.",
    "I can't believe I got fired from the calendar factory. All I did was take a day off.",
    "Why do seagulls fly over the ocean? Because if they flew over the bay, they'd be bagels.",
    "I don’t suffer from insanity; I enjoy every minute of it.",
    "Why did the computer go to the doctor? It had a virus.",
    "I used to be a doctor, but I lost patients.",
    "I’m reading a book about anti-gravity. It’s impossible to put down.",
    "I’m a big fan of whiteboards. They’re re-markable.",
    "Why don't skeletons ever use cell phones? They don’t have the guts to call.",
    "I know a lot of jokes about retired people, but none of them work.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "I’m on a whiskey diet. I’ve lost three days already.",
    "Why don’t we tell secrets in a cornfield? Because the corn have ears.",
    "What do you get if you cross a snowman and a vampire? Frostbite.",
    "I used to play sports, but then I realized you can’t drink beer and play at the same time.",
    "I don’t make mistakes. I make spontaneous creative decisions.",
    "I’m trying to lose weight, but it’s not working out.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "What do you call cheese that isn’t yours? Nacho cheese.",
    "I told my computer I needed a break, and now it won’t stop sending me kit-kats.",
    "I told my wife she was getting too emotional, so she told me to go to my room.",
    "Why was the math book sad? It had too many problems.",
    "What do you call fake spaghetti? An impasta.",
    "I tried to start a hot air balloon business, but it never really took off.",
    "I can’t believe I got fired from the calendar factory. All I did was take a day off.",
    "I don’t trust stairs because they’re always up to something.",
    "What’s orange and sounds like a parrot? A carrot.",
    "Why don’t skeletons fight each other? They don’t have the stomach for it.",
    "How does Moses make his coffee? Hebrews it.",
    "I don’t trust people who do yoga. They’re always stretching the truth.",
    "I used to play piano by ear, but now I use my hands.",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "Why don’t some couples go to the gym? Because some relationships don’t work out.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "I told my dog what’s two minus two. He said nothing.",
    "I used to be a baker, but I couldn’t make enough dough.",
    "I don’t trust people who do acupuncture. They’re back stabbers.",
    "I’m on a whiskey diet. I’ve lost three days already.",
    "Why do seagulls fly over the ocean? Because if they flew over the bay, they’d be bagels.",
    "I can’t trust stairs. They’re always up to something.",
    "What do you call a pile of cats? A meow-tain.",
    "I’m reading a book about anti-gravity. It’s impossible to put down.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "I used to be a velcro salesman, but I couldn’t stick with it.",
    "Why don’t we tell secrets in a cornfield? Because the corn have ears.",
    "I made a pun about the wind, but it blows.",
    "I don't trust people who do yoga. They're always stretching the truth.",
    "Why was the math book sad? It had too many problems.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "What do you call fake spaghetti? An impasta.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "I asked my dog what's two minus two. He said nothing.",
    "I don't trust people who do acupuncture. They're back stabbers.",
    "Why did the computer go to the doctor? It had a virus.",
    "I don't trust stairs. They're always up to something.",
    "Why don't oysters donate to charity? Because they're shellfish."
  ];


  const take = Math.floor(Math.random() * jokes.length); // Random index between 0 and 99
document.getElementsByClassName("box")[0].innerHTML = jokes[take] 